# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf2d64dc593bfcd7dad31efbaa64b68ce82404a265dbaa6f33c7aa5e0d00f6513828748679311753baddb70414efade645516c655ff28f095cfadfeab80e67a2

  stripe_publishable_key: pk_test_pr70xCbgJ02LMQX8pu7V2rdI
  stripe_secret_key: sk_test_4QHVZ0tYxewBuQiPrS5f3V3t


test:
  secret_key_base: 2201f4b00d4c6f0d44fd5ef824ba906abc34a37fcd68a42f39b089afcda4f394888fd5cdaef0cd385525a7e019932c85bd18d53ca3a2c6287eb0f8427672694a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
